HGP-29 : [Refactor] RegionData를 JSON 형태로 바꾼다.
pursWon/AboutRamen pull request #2
Opened 2023-05-10 09:17 UTC by pursWon

카드번호 : [HGP-29](https://jytutoring.atlassian.net/jira/software/c/projects/HGP/boards/1?modal=detail)

RegionData를 JSON 형태로 바꾸고 이에 맞춰서 다른 코드들도 원래의 기능대로 수행되게끔 수정함.

2023-05-10 11:33 UTC, keenkim1202 requested changes
@pursWon 
커밋/푸시하기 전에는 항상 컨벤션을 지켰는지 체크해주세요.
컨벤션을 지키는 것은 기본입니다! 수정 부탁드려요~

PR에서 지적이 나온다면
컨벤션이 아닌 로직이나 기능에 관련된 부분이 나오는 것이 좋은 PR입니다.

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +
불필요한 빈 줄은 제거해주세요~!

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +        guard let regionLocation = regionLocation else { return }
guard문 위에는 한 줄 띄어주세요~

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +                        if i == 0 {
i가 0인 경우만 실행될거라면 for문이 필요없지않을까요?
이전에 리팩토링한 코드를 왜 다시 수정하였나요?

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +        guard let regionLocation = regionLocation else { return }
guard문 위에는 한 줄 띄어주세요~

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/RegionPickerController.swift
> +            guard let regionInformation = try? JSONDecoder().decode(RegionInformation.self, from: region) else
guard문을 두 줄로 쓰신 이유가 있나요?

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/RegionPickerController.swift
> +        guard let regionData = regionData else { return "" }
guard, if, for, switch문 사이에는 한줄 띄어주세요

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/RegionPickerController.swift
> +        guard let regionData = regionData else { return }
guard, if, for, switch문 사이에는 한줄 띄어주세요

2023-05-10 11:33 UTC, keenkim1202 commented on AboutRamen/Model/API/RegionData.swift
> +    guard let fileLocation = Bundle.main.url(forResource: fileName, withExtension: extensionType) else
이 파일은 전반적으로 컨벤션이 모두 맞지 않습니다.
컨벤션 준수해주세요~

2023-05-10 12:31 UTC, pursWon commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +                        if i == 0 {
이거.. 리팩토링 했던 코드인데도 다시 오류가 생겨서 수정했습니다.

2023-05-11 15:08 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +                        if i == 0 {
@pursWon 
그럼 원상복구말고, 오류를 해결해서 커밋해주세요~!

2023-05-11 15:09 UTC, keenkim1202 requested changes

2023-05-11 15:09 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/RegionPickerController.swift
> +        guard let regionData = regionData else { return "" }
@pursWon 107번줄은 왜 띄우신건가요??

2023-05-11 15:09 UTC, keenkim1202 commented on AboutRamen/Controller/HomeTab/RegionPickerController.swift
> +        guard let regionData = regionData else { return }
@pursWon  126번도 왜 띄우신건가요??

2023-05-11 15:20 UTC, pursWon commented on AboutRamen/Controller/HomeTab/HomeViewController.swift
> +                        if i == 0 {
오류 해결했습니다.

2023-05-12 02:33 UTC, keenkim1202 approved these changes

2023-05-12 02:33 UTC, merged